server:
  port: 8761
spring:
  application:
    name: first_eureka_server
  profiles: server1
eureka:
  server:
    enable-self-preservation: false  #解除自我保护模式，加上熔断机制需要设置为true
    eviction-interval-timer-in-ms: 6000 #该字段代表每6s清理一次服务的注册表
  instance:
    lease-renewal-interval-in-seconds: 2 #该字段代表每2s像服务器发送一次心跳
    lease-expiration-duration-in-seconds: 6  #该字段代表如果6s内没有接收到客户端发过来的心跳，则会从实例中清除掉这个实例
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
---
server:
  port: 8762
spring:
  application:
    name: second_eureka_server
  profiles: server2
eureka:
  server:
    enable-self-preservation: false  #解除自我保护模式，加上熔断机制需要设置为true
    eviction-interval-timer-in-ms: 6000 #该字段代表每6s清理一次服务的注册表
  instance:
    lease-renewal-interval-in-seconds: 2 #该字段代表每2s像服务器发送一次心跳
    lease-expiration-duration-in-seconds: 6  #该字段代表如果6s内没有接收到客户端发过来的心跳，则会从实例中清除掉这个实例
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/